services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: aistarter
      POSTGRES_USER: aistarter
      POSTGRES_PASSWORD: aistarter
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aistarter -d aistarter"]
      interval: 5s
      timeout: 5s
      retries: 10

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"

  backend:
    build: ./backend
    env_file: .env
    depends_on:
      - postgres
      - qdrant
    ports:
      - "8000:8000"
    volumes:
      - ./scripts:/app/scripts
      - ./backend/app:/app/app

  frontend:
    build: ./frontend
    env_file: .env
    depends_on:
      - backend
    ports:
      - "3000:3000"
